# 裁定価格理論

## 状態価格と資産価格

ここでは，<span class="markp">**裁定価格理論**(arbitrage pricing theory: APT)において重要な概念である**状態価格**(state price)</span>について説明します。
状態価格を理解するために、無裁定機会について学習します。

まずは次の例をみてみましょう。

:::{.callout-tip}
### 例1

- 今日( $t=0$ )から1年後( $t = 1$ )の状態について2通りの状態(状態1，状態2)が存在し，次のような2つの金融資産($A$，$B$)が存在する。
- 金融資産 $A$ を今日1単位購入すると，1年後に状態 1である場合，キャッシュフロー($CF_A$)として1千円が発生し，状態2である場合には，$CF_A$ は発生しない。
- 金融資産 $B$ を今日1単位購入すると，1年後に状態 1である場合，$CF_B$ は発生しないが，状態2である場合には，1千円の $CF_B$ が発生する。
- 2つの金融資産 $A$，$B$ の今日の価格 $P_A, P_B$ はそれぞれ $0.8$ 千円，$0.6$ 千円である。

ここで，もし金融資産 $C$ が存在し，1年後に状態1である場合には2千円のCFが発生し，状態2である場合には4千円のCFが発生するとき，金融資産Cの価格 $P_C$ はいくらになるか？
:::

まとめると次のような設定になります。

|  状態  |  資産AのCF  |  資産BのCF  |  資産CのCF  |
| ---- | ---- | ---- | ---- |
|  状態1  |  1  |  0  |  2  |
|  状態2  |  0  |  1  |  4  |

- 資産 $A$ : $P_A = 0.8$
- 資産 $B$ : $P_B = 0.6$
- 資産 $C$ : $P_C = ?$


ここで，金融資産Aを2単位，金融資産Bを4単位からなるポートフォリオPを考える。
このポートフォリオPの1年後のCFは，

- 状態1 : $CF_A \times 2 \text{単位}  + CF_B \times 4 \text{単位} = 2 \times 1 + 4 \times 0 = 2$
- 状態2 : $CF_A \times 2 \text{単位}  + CF_B \times 4 \text{単位} = 2 \times 0 + 4 \times 1 = 4$

よって，

1. 金融資産Cの1年後のCFは，ポートフォリオPの1年後のCFと同じ [^1]

**CFが同じなら，価値(価格)は同じ**になるなら，

2. 金融資産Cの価格 $P_C$は，ポートフォリオPの価格となる。よって

$$
P_C = P_A \times 2 + P_B \times 4 = 0.8 \times 2 + 0.6 \times 4 = 4.0
$$

[^1]: このとき金融資産CはポートフォリオPによって**複製される**という。

金融資産Cの価格が $P_C = 3.0$ ならどうなるのか，考えてみましょう。
投資戦略は，資産 $A$を2単位購入し，資産 $B$を4単位空売り，資産 $C$を1.5単位購入するとします。

$t=0$時点でのキャッシュフローは，

$$
0.8 \times 2 + 0.6 \times 4 - 3.0 \times 1.5 = 0
$$

となり， $t=1$ 時点でのキャッシュフローは，

- 状態1 : $- (1 \times 2 + 0 \times 4 + 2.0 \times 1.5) = 1$
- 状態2 : $- (0 \times 2 + 1 \times 4 + 4.0 \times 1.5) = 2$

すなわち，$t = 0$ において，$CF = 0$ でありながら，$t = 1$ 時点において，いずれの状態においても $CF > 0$ が実現できる。
これを**裁定機会(arbitrage opportunity)**という。

このような裁定機会が存在すると，市場参加者はその機会を利用して利益を得ることができるため，市場は効率的でないといえる。


次に，金融資産Cの価格 $P_C = 5.4$ ならどうなるか考えてみよう。

投資戦略は，金融資産Cを1単位空売り，金融資産Aを3.0単位，金融資産Bを5.0単位購入するとします。

$t=0$ 時点でのキャッシュフローは，

$$
5.4 \times 1 - (0.8 \times 3.0 + 0.6 \times 5.0) = 0
$$

となり，$t=1$ 時点でのキャッシュフローは，

- 状態1 : $- 2.0 \times 1 + ( 1.0 \times 3.0 + 0.0 \times 5.0) = 2$
- 状態2 : $- 4.0 \times 1 + ( 0.0 \times 3.0 + 1.0 \times 5.0) = 1$

すなわち，$t=0$ 時点において資金0でありながら，$t=1$ 時点のいずれの状態においても $CF > 0$ が実現できる。
これも裁定機会である。


## 無裁定機会

### 一物一価の法則の下での資産価格

APTでは裁定機会が存在しないと仮定します。
これをノー・フリーランチや一物一価の法則とも呼びます。

<span class="markp">無裁定機会が成立するとき，2つ以上の資産があって，それらの資産が同じCFを生み出すならば，それらの資産価格は同じになる。</span>

$$
\begin{aligned}
\text{金融資産Cの価格} P_C &= \text{ポートフォリオPの価格} \\
 &= 2.0 \times P_A + 4.0 \times P_B\\
 &= 2.0 \times 0.8 + 4.0 \times 0.6 = 4.0
\end{aligned}
$$

<span class="marky">金融資産Aは状態1が発生したときのみ1単位のCFを支払う金融資産</span>であり、<span class="markb">金融資産Bは状態2が発生したときのみ1単位のCFを支払う金融資産</span>である。
このような資産を**状態請求権付き証券**(state-contingent claim)とか**アロー・ドブリュー証券**(A-D証券)という。
A-D証券の現在の価格のことを**状態価格**(state price)という
(上の例では、$P_A = 1.0$、 $P_B = 0.6$ )。
状態価格のベクトルのことを状態価格ベクトルという。
<span class="markp">状態価格は正の値を取る</span>。

### 一物一価の法則と市場均衡

金融資産Cの価格が $P_C = 3.0$ ならば、投資家は高い価格の資産(あるいはポートフォリオ)を空売りし、安い価格の資産(金融資産C)を購入する裁定取引を行おうとする。
したがって、金融資産Cに対する需要が上昇し、金融資産Cの価格が上昇する。

いま、金融資産Cの価格を $P_C = 5.4$ とすると、投資家は金融資産Cを空売りし、安い価格の資産(ポートフォリオ)を購入する裁定取引を行おうとする。
したがって、金融資産Cに対する需要は低下し、金融資産Cの価格が下落する。

金融資産Cの価格を $P_C = 4.0$ とすると、投資家には裁定取引を行う機会がない。したがって、金融資産に対する需要に変化はなく、結果価格も変化しない。
すなわち、<span class="markp">金融資産Cの市場は均衡状態にある</span>。

言い換えると、<span class="marky">一物一価の法則が成立するとき、市場の需給は均衡状態にある</span>。

## 資産価格と状態価格

### 状態価格を用いた資産価格の導出

状態価格ベクトル $(q_1 , \dots , q_M)$ が与えられているとき、裁定機会が存在しない状況下において、ある金融資産の将来CFのベクトル $(D_1, \dots , D_M)$ をA-D証券のポートフォリオを用いて表現することができます。
そして、金融資産の価格は状態価格ベクトルと第1期のCFベクトルとの内積となります。

:::{.callout-tip}
### 例2 : 状態数2のケース

\begin{aligned}
P_C  &= 
\begin{pmatrix}
q_1 & q_2 
\end{pmatrix}
\begin{pmatrix}
D_1 \\
D_2
\end{pmatrix}
\\
& = q_1 D_1 + q_2 D_2 \\
& = 0.8 \times 2 + 0.6 \times 4 \\
& = 4.0
\end{aligned}
:::


:::{.callout-tip}
### 例3 : 状態数4のケース

今日($t=0$)から1年後($t=1$)の状態について4通りのシナリオ(状態1〜状態4)が考えられるとする。
状態価格ベクトルが $(1.0\  0.7\  0.5\  1.2)$ で表されるとき、1年後のCFベクトルが $(1\  5 \  3 \  1)$ となる金融資産の価格 $P_D$ を求めましょう。

$$
\begin{aligned}
P_D  &= 
\begin{pmatrix}
1.0 & 0.7 & 0.5 & 1.2
\end{pmatrix}
\begin{pmatrix}
1 \\
5 \\
3 \\
1
\end{pmatrix}
\\
&= 1.0 \times 1 + 0.7 \times 5 + 0.5 \times 3 + 1.2 \times 1 \\
&= 7.2
\end{aligned}
$$


:::


### まとめ

状態数が$M$であり、状態価格ベクトルが $\boldsymbol{q}^{\top} = (q_1, \dots, q_M)$ 、資産 $i$ のCFベクトルが $\boldsymbol{D}_i = (D_{i,1}, \dots, D_{i,M})$ ならば、資産 $i$ の価格 $P_i$ は次のように表される。

$$
\begin{aligned}
P_i &= \boldsymbol{q}^{\top} \boldsymbol{D}_i \\
    &= q_1 D_{i,1} + \dots + q_M D_{i,M} \\
    &= \sum_{m=1}^{M} q_m D_{i,m}
\end{aligned}
$${#eq-04}

@eq-04 は、状態価格ベクトルを知ることができれば、資産価格を計算できることを示している。

